apiVersion: v2
name: helm-chart-dependency
description: A Helm chart for Kubernetes
dependencies:
- name: kafka
  version: 19.1.3
  repository: https://charts.bitnami.com/bitnami
- name: elasticsearch
  version: 19.5.4
  repository: https://charts.bitnami.com/bitnami
- name: cluster-autoscaler
  version: 9.21.0
  repository: https://kubernetes.github.io/autoscaler
- name: prometheus
  version: 15.18.0
  repository: https://prometheus-community.github.io/helm-charts
- name: grafana
  version: 6.44.2
  repository: https://grafana.github.io/helm-charts
- name: cert-manager
  version: v1.10.0
  repository: https://charts.jetstack.io
  alias: cert-manager
  condition: cert-manager.enabled

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

maintainers:
  - name: Vinit Harsora
    email: harsora.v@northeastern.edu
  - name: Harshal Jaiswal
    email: jaiswal.ha@northeastern.edu
  - name: Shrawani Karpe
    email: karpe.s@northeastern.edu