# A virtual service
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: todo-service
  namespace: istio-system
spec:
  hosts:
    - '*'
  gateways:
    - web-gateway
  http:
    - route:
      - destination:
          host: todo-app.kubernetes-dashboard.svc.cluster.local
          port:
            number: 80